Repository TechnicalTeam-BVCOENM/Abhiyaan, pull requests merged in 2024-09, with the labels that each got.

#247 fix: bug
  lib/app/app.dart
  lib/app/app.logger.dart
  lib/utils/assets_constants.dart
  pubspec.yaml
Labels: Ready

#248 new Quote API integration.
  lib/ui/views/community/community_view.dart
  lib/ui/views/community/community_view_model.dart
Labels: Ready

#249 Email formatter added
  lib/ui/views/auth/register/register_view.dart
  lib/ui/views/auth/register/register_view_model.dart
  lib/ui/views/auth/sign_in/sign_in_view.dart
  lib/ui/views/auth/sign_in/sign_in_view_model.dart
  lib/ui/views/profile/profile_view_component.dart
Labels: Ready

#250 registration StreamBuilder added
  lib/ui/views/auth/auth_view.dart
  lib/ui/views/auth/sign_in/sign_in_view.dart
Labels: Ready

#258 App review modified
  lib/ui/views/profile/profile_view.dart
  lib/ui/views/profile/profile_view_component.dart
  lib/ui/views/profile/profile_view_model.dart
  pubspec.yaml
Labels: help wanted

#261 Onboarding auth view
  lib/ui/views/auth/auth_view.dart
  lib/ui/views/auth/auth_view_model.dart
  lib/ui/views/profile/profile_view_model.dart
Labels: Ready

#268 chore: Context free Dialogs and BottomSheet UI added
  android/app/build.gradle
  android/app/src/main/ic_launcher-playstore.png
  android/app/src/main/res/drawable/ic_launcher_foreground.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/app/src/main/res/values/ic_launcher_background.xml
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner/AppDelegate.swift
  lib/app/app.bottomsheets.dart
  lib/app/app.dart
  lib/app/app.dialogs.dart
  lib/app/app.locator.dart
  lib/app/app.logger.dart
  lib/main.dart
  lib/services/firestore_service.dart
  lib/ui/bottom_sheets/event/event_sheet.dart
  lib/ui/bottom_sheets/event/event_sheet_model.dart
  lib/ui/dialogs/alert/alert_dialog.dart
  lib/ui/dialogs/alert/alert_dialog_model.dart
  lib/ui/views/auth/auth_view.dart
  lib/ui/views/auth/auth_view_model.dart
  lib/ui/views/auth/sign_in/sign_in_view_model.dart
  lib/ui/views/community/community_view_model.dart
  lib/ui/views/community/uni_clubs/uni_clubs_view.dart
  lib/ui/views/community/uni_clubs/uni_clubs_view_components.dart
  lib/ui/views/community/uni_clubs/uni_clubs_view_model.dart
  lib/ui/views/home/home_view_model.dart
  lib/ui/views/profile/preferences/preferences_view.dart
  lib/ui/views/profile/preferences/preferences_view_components.dart
  lib/ui/views/profile/preferences/preferences_view_model.dart
  lib/ui/views/profile/profile_view_component.dart
  lib/ui/views/profile/profile_view_model.dart
  pubspec.yaml
  stacked.json
Labels: Improvemnt, Ready

#267 chore: add crashlytics & app logo
  android/app/build.gradle
  android/app/src/main/ic_launcher-playstore.png
  android/app/src/main/res/drawable/ic_launcher_foreground.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/app/src/main/res/values/ic_launcher_background.xml
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner/AppDelegate.swift
  lib/main.dart
  lib/ui/views/auth/auth_view.dart
  lib/ui/views/auth/auth_view_model.dart
  lib/ui/views/community/uni_clubs/uni_clubs_view.dart
  lib/ui/views/community/uni_clubs/uni_clubs_view_components.dart
  lib/ui/views/community/uni_clubs/uni_clubs_view_model.dart
  lib/ui/views/home/home_view_model.dart
  lib/ui/views/profile/preferences/preferences_view.dart
  lib/ui/views/profile/preferences/preferences_view_components.dart
  lib/ui/views/profile/preferences/preferences_view_model.dart
  lib/ui/views/profile/profile_view_component.dart
  lib/ui/views/profile/profile_view_model.dart
  pubspec.yaml
Labels: Ready

#269 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, Ready

#270 chore: Color modification
  lib/theme/app_color.dart
  lib/ui/common/cached_network_image.dart
  lib/ui/common/carousel_utils.dart
  lib/ui/views/auth/onboarding/onboarding_view.dart
  lib/ui/views/auth/sign_in/sign_in_view.dart
  lib/ui/views/community/clubs/clubs_view_components.dart
  lib/ui/views/community/community_view.dart
  lib/ui/views/community/detailed_blogs/detailed_blogs_view_components.dart
  lib/ui/views/home/home_view.dart
  lib/ui/views/home/home_view_component.dart
  lib/ui/views/profile/preferences/preferences_view.dart
  lib/ui/views/profile/profile_view_component.dart
Labels: Ready

#271 imp: Clubs View
  assets/images/community/avatars/avtr1.jpg
  assets/images/community/avatars/avtr2.jpg
  assets/images/community/avatars/avtr3.jpg
  assets/images/community/avatars/avtr4.jpg
  assets/images/community/verified.svg
  assets/images/community/whatsapp.svg
  lib/app/app.dart
  lib/app/app.dialogs.dart
  lib/app/app.locator.dart
  lib/main.dart
  lib/theme/app_color.dart
  lib/ui/common/section_divider.dart
  lib/ui/dialogs/alert/alert_dialog.dart
  lib/ui/dialogs/alert/alert_dialog_model.dart
  lib/ui/dialogs/alert/logout_dialog.dart
  lib/ui/dialogs/alert/logout_dialog_model.dart
  lib/ui/views/community/community_view.dart
  lib/ui/views/community/community_view_components.dart
  lib/ui/views/community/community_view_model.dart
  lib/ui/views/community/data_model.dart
  lib/ui/views/profile/preferences/preferences_view.dart
  lib/ui/views/profile/preferences/preferences_view_model.dart
  pubspec.yaml
Labels: Design, Ready
