Repository TechnicalTeam-BVCOENM/Abhiyaan, pull requests merged in 2024-08, with the labels that each got.

#236 New Color palette added
  lib/theme/app_color.dart
  lib/ui/views/profile/preferences/preferences_view.dart
  lib/ui/views/profile/preferences/preferences_view_model.dart
Labels: Ready

#237 Profile Page UI Update
  lib/theme/app_font.dart
  lib/ui/views/profile/preferences/preferences_view.dart
  lib/ui/views/profile/preferences/preferences_view_components.dart
  lib/ui/views/profile/profile_view.dart
  lib/ui/views/profile/profile_view_component.dart
  lib/ui/views/profile/profile_view_model.dart
Labels: Ready

#239 Format code in lib
  lib/theme/app_color.dart
  lib/ui/views/auth/auth_view.dart
  lib/ui/views/auth/register/register_view.dart
  lib/ui/views/auth/sign_in/sign_in_view.dart
  lib/ui/views/community/community_view_components.dart
  lib/ui/views/event/event_view.dart
  lib/ui/views/event/gallery/gallery_grid/gallery_view.dart
  lib/ui/views/profile/profile_view_component.dart
  lib/ui/views/profile/profile_view_model.dart
  lib/utils/assets_constants.dart
Labels: Ready

#240 imp: Dialog UI modified
  lib/ui/views/profile/preferences/preferences_view.dart
  lib/ui/views/profile/preferences/preferences_view_components.dart
  lib/ui/views/profile/preferences/preferences_view_model.dart
  lib/ui/views/profile/profile_view.dart
Labels: Improvemnt

#232 feat: Fonts Added
  fonts/Gilroy/Gilroy-Black.ttf
  fonts/Gilroy/Gilroy-Bold.ttf
  fonts/Gilroy/Gilroy-ExtraBold.ttf
  fonts/Gilroy/Gilroy-Heavy.ttf
  fonts/Gilroy/Gilroy-Light.ttf
  fonts/Gilroy/Gilroy-Medium.ttf
  fonts/Gilroy/Gilroy-Regular.ttf
  fonts/Gilroy/Gilroy-SemiBold.ttf
  fonts/Gilroy/Gilroy-Thin.ttf
  lib/theme/app_font.dart
  lib/ui/views/profile/profile_view.dart
  pubspec.yaml
Labels: Change needed

#241 lines design profile background
  assets/images/profile/lines.png
  lib/ui/views/profile/preferences/preferences_view_model.dart
  lib/ui/views/profile/profile_view.dart
  lib/utils/assets_constants.dart
Labels: Ready

#242 Rate app widget
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  lib/ui/views/event/detailed_event/detailed_event_view_model.dart
  lib/ui/views/event/event_view_model.dart
  lib/ui/views/profile/profile_view.dart
  lib/ui/views/profile/profile_view_component.dart
  lib/ui/views/profile/profile_view_model.dart
  pubspec.yaml
Labels: Ready
